apiVersion: v1
kind: Service
metadata:
  name: kafka-ilb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
     app: cp-kafka-rest
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
